import {
  BarChart3,
  Calendar,
  CheckCircle,
  Cpu,
  ClipboardIcon,
  Compass,
  Database,
  Flag,
  Headphones,
  Home,
  Info,
  Link2,
  Lock,
  MessageCircle,
  Bell,
  CreditCard,
  Power,
  Receipt,
  Shield,
  Star,
  Settings,
  Video,
  Wallet,
  AlertTriangle,
  Send,
  GitBranch,
  User,
  LayoutGrid,
  Contact,
} from "lucide-react";

export const icons = [
  { value: "chart", path: BarChart3 },
  { value: "calendar", path: Calendar },
  { value: "check", path: CheckCircle },
  { value: "chip", path: Cpu },
  { value: "compass", path: Compass },
  { value: "database", path: Database },
  { value: "flag", path: Flag },
  { value: "headphone", path: Headphones },
  { value: "home", path: Home },
  { value: "info", path: Info },
  { value: "link", path: Link2 },
  { value: "lock", path: Lock },
  { value: "messages", path: MessageCircle },
  { value: "notification", path: Bell },
  { value: "payment", path: CreditCard },
  { value: "power", path: Power },
  { value: "receipt", path: Receipt },
  { value: "shield", path: Shield },
  { value: "star", path: Star },
  { value: "settings", path: Settings },
  { value: "videorecorder", path: Video },
  { value: "wallet", path: Wallet },
  { value: "warning", path: AlertTriangle },
  { value: "send", path: Send },
  { value: "pipelines", path: GitBranch },
  { value: "person", path: User },
  { value: "category", path: LayoutGrid },
  { value: "contact", path: Contact },
  { value: "clipboardIcon", path: ClipboardIcon },
];

export const pricingCards = [
  {
    title: "Starter",
    description: "Perfect for trying out plura",
    price: "Free",
    duration: "",
    highlight: "Key features",
    features: ["3 Sub accounts", "2 Team members", "Unlimited pipelines"],
    priceId: "",
  },
  {
    title: "Unlimited Saas",
    description: "The ultimate agency kit",
    price: "$199",
    duration: "month",
    highlight: "Key features",
    features: [
      "Rebilling",
      "24/7 Support team",
      "Unlimited Sub accounts",
      "Unlimited Team members",
      "Unlimited pipelines",
    ],
    priceId: "price_1TNTZ9Rntb86KzsEg5BphfeE",
  },
  {
    title: "Basic",
    description: "For serious agency owners",
    price: "$49",
    duration: "month",
    highlight: "Everything in Starter, plus",
    features: ["Unlimited Sub accounts", "Unlimited Team members", "Unlimited pipelines"],
    priceId: "price_1TNTZARntb86KzsECaoSE8MJ",
  },
];
